# NumPy Tutorial: Learn NumPy in 30 Minutes

This notebook provides a comprehensive introduction to NumPy, the fundamental package for scientific computing in Python.

**What is NumPy?**
- NumPy (Numerical Python) is a library for the Python programming language
- It provides support for large, multi-dimensional arrays and matrices
- Includes a collection of mathematical functions to operate on these arrays
- Essential for data science, machine learning, and scientific computing

**Learning Objectives:**
1. Understand NumPy arrays and their advantages
2. Create and manipulate arrays
3. Perform mathematical and statistical operations
4. Use indexing and slicing effectively
5. Apply NumPy to real-world problems


In [2]:
# Import NumPy - convention is to import as np
import numpy as np


## 1. Why NumPy? Comparing Lists vs NumPy Arrays

NumPy arrays are more efficient than Python lists for numerical operations.


In [5]:
# Python list
python_list = [1, 2, 3, 4, 5]

# NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])

print("Python list:", python_list)
print("NumPy array:", numpy_array)
print("\nType of Python list:", type(python_list))
print("Type of NumPy array:", type(numpy_array))

# Key advantage: Vectorized operations (no loops needed!)
# Adding 10 to each element
print("Python list (requires loop):", [x + 10 for x in python_list])
print("NumPy array (vectorized):", numpy_array + 10)


Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]

Type of Python list: <class 'list'>
Type of NumPy array: <class 'numpy.ndarray'>
Python list (requires loop): [11, 12, 13, 14, 15]
NumPy array (vectorized): [11 12 13 14 15]


In [6]:
import time

# Large arrays
size = 1000000
python_list = list(range(size))
numpy_array = np.arange(size)

# Addition operation
print("--- Performance Comparison ---")
print(f"Array size: {size:,} elements\n")

# Python list (using list comprehension)
start = time.time()
result_python = [x + 1 for x in python_list]
time_python = time.time() - start
print(f"Python list addition: {time_python:.6f} seconds")

# NumPy array (vectorized)
start = time.time()
result_numpy = numpy_array + 1
time_numpy = time.time() - start
print(f"NumPy array addition: {time_numpy:.6f} seconds")
print(f"\nNumPy is {time_python/time_numpy:.1f}x faster!")


--- Performance Comparison ---
Array size: 1,000,000 elements

Python list addition: 0.035624 seconds
NumPy array addition: 0.001001 seconds

NumPy is 35.6x faster!


## 2. Creating NumPy Arrays

There are several ways to create NumPy arrays.


In [7]:
# Method 1: From Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("From list:", arr1)

# Method 2: Using np.arange() - similar to range()
arr2 = np.arange(0, 10, 2)  # start, stop, step
print("Using arange:", arr2)

# Method 3: Using np.linspace() - evenly spaced numbers
arr3 = np.linspace(0, 1, 5)  # start, stop, number of elements
print("Using linspace:", arr3)

# Method 4: Creating arrays of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# Method 5: Creating arrays of ones
ones = np.ones(5)
print("Ones:", ones)

# Method 6: Creating arrays with a specific value
full = np.full(5, 7)  # shape, fill_value
print("Full (all 7s):", full)

# Method 7: Identity matrix
identity = np.eye(3)
print("Identity matrix:\n", identity)

# Method 8: Random arrays
random_arr = np.random.rand(5)  # Uniform distribution [0, 1)
print("Random (uniform):", random_arr)

random_int = np.random.randint(1, 10, size=5)  # [low, high), size
print("Random integers:", random_int)


From list: [1 2 3 4 5]
Using arange: [0 2 4 6 8]
Using linspace: [0.   0.25 0.5  0.75 1.  ]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Full (all 7s): [7 7 7 7 7]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random (uniform): [0.25026797 0.80276859 0.34065976 0.62308228 0.02074013]
Random integers: [4 5 2 2 5]


## 3. NumPy Data Types (dtype)

NumPy arrays are homogeneous - all elements have the same type. Types affect memory usage and operations.


In [11]:
# Type inference and common types
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])
arr_mixed = np.array([1, 2.5, 3])  # Mixed types → promoted to float

print(f"Integer: {arr_int.dtype}")
print(f"Float: {arr_float.dtype}")
print(f"Mixed: {arr_mixed.dtype}  (promoted to float)\n")

# Specifying types
arr1 = np.array([1, 2, 3], dtype=np.float32)
arr2 = arr_int.astype(np.float64)  # Convert types

print(f"Specified float32: {arr1.dtype}")
print(f"Converted to float64: {arr2.dtype}\n")

# Common types: int32, int64, float32, float64, bool
print("Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element")


Integer: int32
Float: float64
Mixed: float64  (promoted to float)

Specified float32: float32
Converted to float64: float64

Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element


## 4. Multi-dimensional Arrays

In [15]:

# 2D array (matrix)
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix):")
print(matrix_2d)
print(f"Shape: {matrix_2d.shape}")  # (rows, columns)
print(f"Dimensions: {matrix_2d.ndim}")  # Number of dimensions
print(f"Size: {matrix_2d.size}")  # Total number of elements
print(f"Data type: {matrix_2d.dtype}")  # Data type of elements

# 3D array
matrix_3d = np.array([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
print("\n3D Array:")
print(matrix_3d)
print(f"Shape: {matrix_3d.shape}")  # (depth, rows, columns)

# Creating multi-dimensional arrays with specific shapes
zeros_2d = np.zeros((3, 4))  # 3 rows, 4 columns
print("\n2D zeros array:")
print(zeros_2d)

ones_3d = np.ones((2, 3, 4))  # 2x3x4 array
print(ones_3d)
print(f"\n3D ones array shape: {ones_3d.shape}")


2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int32

3D Array:
[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
Shape: (2, 2, 3)

2D zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

3D ones array shape: (2, 3, 4)


## 5. Array Attributes and Information

Understanding array properties is crucial for working with NumPy.


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array:")
print(arr)
print(f"\nShape: {arr.shape}")  # Dimensions of the array
print(f"Size: {arr.size}")  # Total number of elements
print(f"ndim: {arr.ndim}")  # Number of dimensions
print(f"dtype: {arr.dtype}")  # Data type
print(f"itemsize: {arr.itemsize} bytes")  # Size of each element
print(f"nbytes: {arr.nbytes} bytes")  # Total memory used
print(f"T (transpose):\n{arr.T}")  # Transpose of the array


## 6. Indexing and Slicing

Accessing and modifying array elements is similar to Python lists, but more powerful.


In [18]:
arr = np.array([10, 20, 30, 40, 50])

# 1D indexing (same as Python lists)
print("Original array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements 1 to 3:", arr[1:4])  # Slicing: [start:stop:step]
print("Every other element:", arr[::2])

# 2D indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(matrix)
print("Element at row 1, column 2:", matrix[1, 2])  # Row, Column
print("First row:", matrix[0, :])  # All columns of first row
print("Second column:", matrix[:, 1])  # All rows of second column
print("Submatrix (first 2 rows, first 2 columns):")
print(matrix[0:2, 0:2])

# Boolean indexing - powerful feature!
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n--- Boolean Indexing ---")
print("Original:", arr)
print("Elements greater than 5:", arr[arr > 5])
print("Even numbers:", arr[arr % 2 == 0])


Original array: [10 20 30 40 50]
First element: 10
Last element: 50
Elements 1 to 3: [20 30 40]
Every other element: [10 30 50]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Submatrix (first 2 rows, first 2 columns):
[[1 2]
 [4 5]]

--- Boolean Indexing ---
Original: [ 1  2  3  4  5  6  7  8  9 10]
Elements greater than 5: [ 6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]


## 7. Array Operations: Mathematical Operations

NumPy supports element-wise operations without loops.


In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Array a:", a)
print("Array b:", b)

# Element-wise operations
print("\n--- Element-wise Operations ---")
print("Addition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)  # Element-wise, NOT matrix multiplication
print("Division (a / b):", a / b)
print("Square root:", np.sqrt(a))

# Scalar operations (broadcasting)
print("\n--- Scalar Operations ---")
print("a + 10:", a + 10)
print("a * 2:", a * 2)
print("a ** 3:", a ** 3)

# Comparison operations
print("\n--- Comparison Operations ---")
print("a > 2:", a > 2)
print("a == 3:", a == 3)
print("a <= 2:", a <= 2)


Array a: [1 2 3 4]
Array b: [5 6 7 8]

--- Element-wise Operations ---
Addition (a + b): [ 6  8 10 12]
Subtraction (a - b): [-4 -4 -4 -4]
Multiplication (a * b): [ 5 12 21 32]
Division (a / b): [0.2        0.33333333 0.42857143 0.5       ]
Square root: [1.         1.41421356 1.73205081 2.        ]

--- Scalar Operations ---
a + 10: [11 12 13 14]
a * 2: [2 4 6 8]
a ** 3: [ 1  8 27 64]

--- Comparison Operations ---
a > 2: [False False  True  True]
a == 3: [False False  True False]
a <= 2: [ True  True False False]


## 8. Array Manipulation: Reshaping and Resizing

Changing the shape of arrays is common in data processing.


In [27]:
arr = np.arange(12)
print("Original 1D array:", arr)

# Reshape - changes view, doesn't copy data
reshaped = arr.reshape(3, 4)  # Must match total size (3*4=12)
print("\nReshaped to 3x4:")
print(reshaped)

# Flatten - convert to 1D
flattened = reshaped.flatten()
print("\nFlattened:", flattened)

# Reshape with -1 (auto-calculate dimension)
auto_reshape = arr.reshape(2, -1)  # -1 means "calculate automatically"
print("\nAuto reshape (2 rows, auto columns):")
print(auto_reshape)

# Transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal matrix:")
print(matrix)
print("Transposed:")
print(matrix.T)

# Concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("\n--- Concatenation ---")
print("Array a:\n", a)
print("Array b:\n", b)
print("Vertical concatenation (vstack):")
print(np.vstack((a, b)))
print("Horizontal concatenation (hstack):")
print(np.hstack((a, b)))
print("Using concatenate:")
print(np.concatenate((a, b), axis=0))  # axis=0 for vertical
print(np.concatenate((a, b), axis=1))  # axis=1 for horizontal


Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Auto reshape (2 rows, auto columns):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed:
[[1 4]
 [2 5]
 [3 6]]

--- Concatenation ---
Array a:
 [[1 2]
 [3 4]]
Array b:
 [[5 6]
 [7 8]]
Vertical concatenation (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal concatenation (hstack):
[[1 2 5 6]
 [3 4 7 8]]
Using concatenate:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## 9. Understanding Dimensions and Axis

**Key Concepts:**
- **Dimension (ndim)**: Number of axes (1D=1, 2D=2, 3D=3)
- **Axis**: The dimension along which an operation is performed (starts at 0)
- **Shape**: Size of each dimension (e.g., (3, 4) = 3 rows, 4 columns)
- **For 2D arrays**: `axis=0` = rows (vertical), `axis=1` = columns (horizontal)


In [ ]:
# Understanding dimensions
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:")
print(f"  {arr_1d} → shape: {arr_1d.shape}, ndim: {arr_1d.ndim} (axis 0 only)\n")

print("2D Array:")
print(f"  {arr_2d}")
print(f"  shape: {arr_2d.shape} (rows, columns)")
print(f"  ndim: {arr_2d.ndim} (axis 0=rows, axis 1=columns)")


In [28]:
# Axis in operations: specifies which dimension to collapse
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}\n")

# axis=0: collapse rows (operate down columns) → one value per column
sum_axis0 = np.sum(matrix, axis=0)
print(f"axis=0 (down rows): {sum_axis0}  → shape: {sum_axis0.shape}")
print(f"  Example: Column 0 sum = {matrix[0,0]} + {matrix[1,0]} + {matrix[2,0]} = {sum_axis0[0]}\n")

# axis=1: collapse columns (operate across rows) → one value per row
sum_axis1 = np.sum(matrix, axis=1)
print(f"axis=1 (across columns): {sum_axis1}  → shape: {sum_axis1.shape}")
print(f"  Example: Row 0 sum = {matrix[0,0]} + {matrix[0,1]} + {matrix[0,2]} = {sum_axis1[0]}\n")


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

axis=0 (down rows): [12 15 18]  → shape: (3,)
  Example: Column 0 sum = 1 + 4 + 7 = 12

axis=1 (across columns): [ 6 15 24]  → shape: (3,)
  Example: Row 0 sum = 1 + 2 + 3 = 6



In [29]:
# 3D Arrays: Axis with more than 2 dimensions
# Think: (depth, rows, columns) or (samples, height, width)
arr_3d = np.array([
    [[1, 2, 3],    # First 2D slice (page 0)
     [4, 5, 6]],
    [[7, 8, 9],    # Second 2D slice (page 1)
     [10, 11, 12]]
])

print("3D Array (shape: 2x2x3):")
print("Think: 2 pages, each with a 2x3 matrix")
print(arr_3d)
print(f"Shape: {arr_3d.shape}  (depth=2, rows=2, columns=3)\n")

# axis=0: collapse depth (across pages) → result: 2D (2×3)
sum_axis0 = np.sum(arr_3d, axis=0)
print(f"axis=0 (across pages):\n{sum_axis0}  → shape: {sum_axis0.shape}")
print(f"  Example: [0,0,0] = {arr_3d[0,0,0]} + {arr_3d[1,0,0]} = {sum_axis0[0,0]}\n")

# axis=1: collapse rows (down each page) → result: 2D (2×3)
sum_axis1 = np.sum(arr_3d, axis=1)
print(f"axis=1 (down rows):\n{sum_axis1}  → shape: {sum_axis1.shape}")
print(f"  Example: [0,0] = {arr_3d[0,0,0]} + {arr_3d[0,1,0]} = {sum_axis1[0,0]}\n")

# axis=2: collapse columns (across each row) → result: 2D (2×2)
sum_axis2 = np.sum(arr_3d, axis=2)
print(f"axis=2 (across columns):\n{sum_axis2}  → shape: {sum_axis2.shape}")
print(f"  Example: [0,0] = {arr_3d[0,0,0]} + {arr_3d[0,0,1]} + {arr_3d[0,0,2]} = {sum_axis2[0,0]}\n")


3D Array (shape: 2x2x3):
Think: 2 pages, each with a 2x3 matrix
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)  (depth=2, rows=2, columns=3)

axis=0 (across pages):
[[ 8 10 12]
 [14 16 18]]  → shape: (2, 3)
  Example: [0,0,0] = 1 + 7 = 8

axis=1 (down rows):
[[ 5  7  9]
 [17 19 21]]  → shape: (2, 3)
  Example: [0,0] = 1 + 4 = 5

axis=2 (across columns):
[[ 6 15]
 [24 33]]  → shape: (2, 2)
  Example: [0,0] = 1 + 2 + 3 = 6



## 10. Statistical Operations

NumPy provides many statistical functions.


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Array:", arr)

# Basic statistics
print(f"\n--- Basic Statistics ---")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Index of min: {np.argmin(arr)}")
print(f"Index of max: {np.argmax(arr)}")

# 2D array statistics (with axis parameter)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n--- 2D Array Statistics ---")
print("Matrix:")
print(matrix)
print(f"Sum of all elements: {np.sum(matrix)}")
print(f"Sum along rows (axis=0): {np.sum(matrix, axis=0)}")  # Column sums
print(f"Sum along columns (axis=1): {np.sum(matrix, axis=1)}")  # Row sums
print(f"Mean of each column: {np.mean(matrix, axis=0)}")
print(f"Mean of each row: {np.mean(matrix, axis=1)}")


## 11. Linear Algebra Operations

NumPy includes powerful linear algebra functions.


In [31]:
# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix a:")
print(a)
print("\nMatrix b:")
print(b)

# Element-wise multiplication (NOT matrix multiplication)
print("\nElement-wise multiplication (a * b):")
print(a * b)

# Dot product of vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(f"\nDot product of vectors {v1} and {v2}: {np.dot(v1, v2)}")

# Matrix properties
matrix = np.array([[1, 2], [3, 4]])
print("\n--- Matrix Properties ---")
print("Matrix:")
print(matrix)
print(f"Determinant: {np.linalg.det(matrix)}")
print(f"Inverse:")
print(np.linalg.inv(matrix))
print(f"Transpose:")
print(matrix.T)

# Eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(matrix)
print(f"\nEigenvalues: {eigenvals}")
print(f"Eigenvectors:\n{eigenvecs}")


Matrix a:
[[1 2]
 [3 4]]

Matrix b:
[[5 6]
 [7 8]]

Element-wise multiplication (a * b):
[[ 5 12]
 [21 32]]

Dot product of vectors [1 2 3] and [4 5 6]: 32

--- Matrix Properties ---
Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Transpose:
[[1 3]
 [2 4]]

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 12. Useful Array Functions

Common utility functions for array manipulation.


In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print("Original array:", arr)

# Sorting
print("\n--- Sorting ---")
print("Sorted array:", np.sort(arr))  # Returns sorted copy
print("Original unchanged:", arr)
arr.sort()  # In-place sort
print("After in-place sort:", arr)

# Unique elements
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
print("\n--- Unique Elements ---")
print("Array:", arr_with_duplicates)
print("Unique values:", np.unique(arr_with_duplicates))

# Searching
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n--- Searching ---")
print("Array:", arr)
print("Where is value > 5?", np.where(arr > 5))
print("Values where condition is True:", arr[np.where(arr > 5)])

# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\n--- Stacking ---")
print("Array a:", a)
print("Array b:", b)
print("Stack vertically:", np.vstack((a, b)))
print("Stack horizontally:", np.hstack((a, b)))
print("Stack as columns:", np.column_stack((a, b)))


Original array: [3 1 4 1 5 9 2 6]

--- Sorting ---
Sorted array: [1 1 2 3 4 5 6 9]
Original unchanged: [3 1 4 1 5 9 2 6]
After in-place sort: [1 1 2 3 4 5 6 9]

--- Unique Elements ---
Array: [1 2 2 3 3 3 4]
Unique values: [1 2 3 4]

--- Searching ---
Array: [ 1  2  3  4  5  6  7  8  9 10]
Where is value > 5? (array([5, 6, 7, 8, 9], dtype=int64),)
Values where condition is True: [ 6  7  8  9 10]

--- Stacking ---
Array a: [1 2 3]
Array b: [4 5 6]
Stack vertically: [[1 2 3]
 [4 5 6]]
Stack horizontally: [1 2 3 4 5 6]
Stack as columns: [[1 4]
 [2 5]
 [3 6]]


## 13. Practical Example: Image Processing Simulation

Let's apply NumPy to simulate basic image processing operations.


In [33]:
# Simulate a grayscale image (2D array) with values 0-255
# Let's create a simple 10x10 "image"
image = np.random.randint(0, 256, size=(10, 10))
print("Original 'image' (10x10 array):")
print(image)

# Image operations
print(f"\n--- Image Statistics ---")
print(f"Brightness (mean): {np.mean(image):.2f}")
print(f"Contrast (std): {np.std(image):.2f}")
print(f"Min pixel value: {np.min(image)}")
print(f"Max pixel value: {np.max(image)}")

# Brightness adjustment (add constant)
brighter = np.clip(image + 50, 0, 255)  # Clip to valid range
print(f"\nBrightness increased (mean: {np.mean(brighter):.2f})")

# Contrast adjustment (multiply)
contrast = np.clip(image * 1.5, 0, 255)
print(f"Contrast increased (std: {np.std(contrast):.2f})")


Original 'image' (10x10 array):
[[185 126  63 168  68 255 152 103  53  18]
 [ 31 241 105  20  92  86  75  12 127 137]
 [ 59  45 122 218 135 121 180 155 193 236]
 [178 150 104 130 139 172 137  57 215  83]
 [227 130 210   2 145 136 114 183 209  37]
 [153 238  98 140 176 225  60 166  42 215]
 [ 86  76 213 167 111 238 121 228 227 192]
 [227 237 222 130   3  50 143  28 129  78]
 [ 31 122  34 204 113 198 151  67  20  93]
 [ 21 141 117 101 212 209 128 250 142 121]]

--- Image Statistics ---
Brightness (mean): 132.33
Contrast (std): 67.72
Min pixel value: 2
Max pixel value: 255

Brightness increased (mean: 177.86)
Contrast increased (std: 77.30)


## 14. Practical Example: Data Analysis

Analyzing a dataset using NumPy operations.


In [34]:
# Simulate student test scores (3 tests, 5 students)
scores = np.array([
    [85, 90, 88],  # Student 1
    [92, 87, 91],  # Student 2
    [78, 82, 80],  # Student 3
    [95, 98, 96],  # Student 4
    [88, 85, 90]   # Student 5
])

print("Test Scores Matrix (5 students, 3 tests):")
print(scores)

# Calculate statistics
print("\n--- Student Statistics ---")
student_averages = np.mean(scores, axis=1)
print("Average score per student:", student_averages)
print("Best student average:", np.max(student_averages))
print("Student with best average (index):", np.argmax(student_averages))

print("\n--- Test Statistics ---")
test_averages = np.mean(scores, axis=0)
print("Average score per test:", test_averages)
print("Hardest test (lowest average):", np.argmin(test_averages))
print("Easiest test (highest average):", np.argmax(test_averages))

# Find students who scored above 90 in all tests
excellent_students = np.all(scores > 90, axis=1)
print("\n--- Excellent Students (all tests > 90) ---")
print("Boolean mask:", excellent_students)
print("Indices:", np.where(excellent_students)[0])
print("Scores of excellent students:")
print(scores[excellent_students])


Test Scores Matrix (5 students, 3 tests):
[[85 90 88]
 [92 87 91]
 [78 82 80]
 [95 98 96]
 [88 85 90]]

--- Student Statistics ---
Average score per student: [87.66666667 90.         80.         96.33333333 87.66666667]
Best student average: 96.33333333333333
Student with best average (index): 3

--- Test Statistics ---
Average score per test: [87.6 88.4 89. ]
Hardest test (lowest average): 0
Easiest test (highest average): 2

--- Excellent Students (all tests > 90) ---
Boolean mask: [False False False  True False]
Indices: [3]
Scores of excellent students:
[[95 98 96]]


## 15. Common NumPy Functions Cheat Sheet

Quick reference for frequently used NumPy functions.


In [ ]:
# Array Creation
# np.array(), np.arange(), np.linspace(), np.zeros(), np.ones()
# np.full(), np.eye(), np.random.rand(), np.random.randint()

# Array Information
# .shape, .size, .ndim, .dtype, .itemsize, .nbytes

# Array Manipulation
# .reshape(), .flatten(), .T (transpose)
# np.concatenate(), np.vstack(), np.hstack()
# np.split(), np.array_split()

# Mathematical Operations
# +, -, *, /, **, %, np.sqrt(), np.sin(), np.cos(), np.exp(), np.log()

# Statistical Functions
# np.sum(), np.mean(), np.median(), np.std(), np.var()
# np.min(), np.max(), np.argmin(), np.argmax()
# np.percentile(), np.quantile()

# Linear Algebra
# np.dot(), @ (matrix multiplication)
# np.linalg.det(), np.linalg.inv(), np.linalg.eig()
# np.linalg.solve() (solve linear equations)

# Searching and Sorting
# np.where(), np.argwhere()
# np.sort(), .sort() (in-place)
# np.unique(), np.searchsorted()

# Array Comparison
# ==, !=, <, >, <=, >=
# np.all(), np.any(), np.isnan(), np.isinf()
